name: docker-build

on:
  push:
  pull_request:

env:
  SHOULD_PUSH: ${{ forgejo.event_name == 'push' && forgejo.ref == 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to registry
        if: ${{ env.SHOULD_PUSH }}
        uses: docker/login-action@v4
        with:
          registry: git.milkshake.services
          username: ${{ forgejo.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: linux/amd64
          push: ${{ env.SHOULD_PUSH }}
          tags: git.milkshake.services/floatingmilkshake/mechanicalmilkshake:latest
